---
name: ci
on:
  push:
    branches:
      - actions
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 5 * * *'

jobs:
  bazel_macos:
    name: bazel macos latest
    runs-on: macos-latest
    steps:
      - name: setup
        run: |
          brew update
          brew uninstall -q bazelisk
          brew install -q \
            bazel \
            git
        shell: zsh -efuo pipefail {0}
      - name: checkout
        uses: actions/checkout@v2
      - name: build and test
        run: bazel test ...
        shell: zsh -efuo pipefail {0}

  bazel_ubuntu:
    name: bazel ubuntu latest
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: setup
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get install -o Dpkg::Use-Pty=0 -qq --no-install-recommends \
            ca-certificates \
            g++ \
            git \
            gnupg \
            python-is-python3
          export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
          apt-key adv -q --fetch-keys https://bazel.build/bazel-release.pub.gpg
          echo 'deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8' \
            > /etc/apt/sources.list.d/bazel.list
          apt-get update -qq
          apt-get install -o Dpkg::Use-Pty=0 -qq --no-install-recommends bazel
        shell: bash
      - name: checkout
        uses: actions/checkout@v2
      - name: build and test
        run: bazel test ...
        shell: bash

  cmake_macos:
    name: cmake macos latest
    runs-on: macos-latest
    steps:
      - name: setup
        run: |
          brew update
          brew install -q \
            cmake \
            doxygen \
            git \
            pkg-config
        shell: zsh -efuo pipefail {0}
      - name: checkout
        uses: actions/checkout@v2
      - name: build and test
        run: |
          mkdir _build
          cd _build
          cmake \
            -DBUILD_DOCUMENTATION:BOOL=ON \
            -DBUILD_TESTING:BOOL=ON \
            -DCMAKE_INSTALL_PREFIX:PATH=_install \
            -DENABLE_HARDENING:BOOL=ON \
            -DENABLE_INTERPROCEDURAL_OPTIMIZATION:BOOL=ON \
            -DENABLE_OPENMP:BOOL=OFF \
            -DOUTPUT_TIME_AND_POSITIONS:BOOL=OFF \
            -DSEED_RANDOM_NUMBER_GENERATOR:BOOL=OFF \
            --warn-uninitialized \
            ..
          cmake --build .
          ctest .
          cmake --install .
        shell: zsh -efuo pipefail {0}

  cmake_ubuntu:
    name: cmake ubuntu latest
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: setup
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get install -o Dpkg::Use-Pty=0 -qq --no-install-recommends \
            ca-certificates \
            doxygen \
            g++ \
            git \
            gnupg \
            lsb-release
            make \
            pkg-config
          export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
          apt-key adv -q --fetch-keys \
            https://apt.kitware.com/keys/kitware-archive-latest.asc
          echo "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" \
            > /etc/apt/sources.list.d/kitware.list
          apt-get update -qq
          apt-get install -o Dpkg::Use-Pty=0 -qq --no-install-recommends cmake
        shell: bash
      - name: checkout
        uses: actions/checkout@v2
      - name: build and test
        run: |
          mkdir _build
          cd _build
          cmake \
            -DBUILD_DOCUMENTATION:BOOL=ON \
            -DBUILD_TESTING:BOOL=ON \
            -DCMAKE_INSTALL_PREFIX:PATH=_install \
            -DENABLE_HARDENING:BOOL=ON \
            -DENABLE_INTERPROCEDURAL_OPTIMIZATION:BOOL=ON \
            -DENABLE_OPENMP:BOOL=ON \
            -DOUTPUT_TIME_AND_POSITIONS:BOOL=OFF \
            -DSEED_RANDOM_NUMBER_GENERATOR:BOOL=OFF \
            --warn-uninitialized \
            ..
          cmake --build .
          ctest .
          cmake --install .
        shell: bash

  cmake_windows:
    name: cmake windows latest
    runs-on: windows-latest
    steps:
      - name: setup
        run: |
          cinst cmake.install --install-arguments='ADD_CMAKE_TO_PATH=System'
          cinst doxygen.install git.install
        shell: powershell
      - name: checkout
        uses: actions/checkout@v2
      - name: build and test
        run: |
          mkdir _build
          cd _build
          cmake `
            -DBUILD_DOCUMENTATION:BOOL=ON `
            -DBUILD_TESTING:BOOL=ON `
            -DCMAKE_INSTALL_PREFIX:PATH=_install `
            -DENABLE_HARDENING:BOOL=OFF `
            -DENABLE_INTERPROCEDURAL_OPTIMIZATION:BOOL=ON `
            -DENABLE_OPENMP:BOOL=OFF `
            -DOUTPUT_TIME_AND_POSITIONS:BOOL=OFF `
            -DSEED_RANDOM_NUMBER_GENERATOR:BOOL=OFF `
            --warn-uninitialized `
            ..
          cmake --build . --config Release
          ctest . --build-config Release
          cmake --install .
        shell: powershell
